### ISSUE TITLE
Set up Study Hub Resource Schema for Publish Action V.1

### ISSUE THREAD

**Issue by ReneHaensel** [nfdi4health/seek#23]
Schema (JSON) ableiten aus MDS Version 2.1 ( bei JD erfragen?)
Siehe auch: https://csh.nfdi4health.de/mdr/studyhub_resources

**Comment by johannes-darms** [comment]
Hallo Rene, 
ich habe dieses Schema erzeugt um damit meine Konverter zu validieren.
https://github.com/nfdi4health/csh-etl-pipeline/blob/MDS2.1/etljobs/converter/MDS.json

**Comment by knoppiks** [comment]
We can use
https://github.com/nfdi4health/seek/blob/main/public/api/mds_json_schema_study_interventional.json
https://github.com/nfdi4health/seek/blob/main/public/api/mds_json_schema_study_non_interventional.json
https://github.com/nfdi4health/seek/blob/main/public/api/mds_non_study_schema.json
